/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RuntimeInterface */

#ifndef _Included_RuntimeInterface
#define _Included_RuntimeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RuntimeInterface
 * Method:    getMapTile
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_RuntimeInterface_getMapTile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     RuntimeInterface
 * Method:    setMapActiveTile
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_RuntimeInterface_setMapActiveTile
  (JNIEnv *, jobject, jint);

/*
 * Class:     RuntimeInterface
 * Method:    debug_stdout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RuntimeInterface_debug_1stdout
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
